package com.forgestorm.bitmasking.demo;

import lombok.Getter;
import lombok.Setter;

/**
 * Basic representation of a tile.
 */
public class Tile {

    /**
     * The ID set here was generated by {@link AbstractWangTile} autoTile(int x, int y) method.
     */
    @Setter
    @Getter
    private int autoTileID;

    public Tile(int autoTileID) {
        this.autoTileID = autoTileID;
    }
}
